# Site settings
name: Welcome
title: Taikgun Song
email: songt@iastate.edu
# Build settings
markdown: kramdown
url: http://localhost:4000
markdown: kramdown
navigation:
- text: Home
  url: /index.html